name: Run Modified SQL Files on Snowflake

on:
  push:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  run-modified-sql:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
          echo "$HOME/bin" >> $GITHUB_PATH
          
      - name: Debug Commit Values
        run: |
              echo "Before commit: ${GITHUB_EVENT_BEFORE}"
              echo "Current commit: ${GITHUB_SHA}"
               
      # Step 2: Detect modified SQL files between the current and previous commits
      - name: Detect Modified SQL Files
        id: modified_files
        run: |

          PREV_COMMIT=$(git rev-parse HEAD^)
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Previous commit: $PREV_COMMIT"
          echo "Current commit: $CURRENT_COMMIT"

          git diff --name-only --diff-filter=ACMRT $PREV_COMMIT $CURRENT_COMMIT -- '*.sql' > modified_sql_files.txt

          # Check if any SQL files were found and set environment variable
            if [ -s modified_sql_files.txt ]; then
            sql_files=$(cat modified_sql_files.txt | tr '\n' ' ')
            echo "sql_files=$sql_files" >> $GITHUB_ENV
            else
            echo "No SQL files modified."
            echo "sql_files=" >> $GITHUB_ENV
            fi
        
      # Step 3: Print the output of the previous step
      - name: Print Modified SQL Files
        run: |
          echo "The modified SQL files are: ${{ env.sql_files }}"

      - name: Set up SnowSQL Config File
        run: |
          # Create the .snowsql directory
          mkdir -p $HOME/.snowsql
          
          # Create the configuration file with your details
          echo "[connections.snowflake_connect]" > $HOME/.snowsql/config
          echo "accountname = ${{ secrets.SF_ACCOUNT }}" >> $HOME/.snowsql/config
          echo "username = ${{ secrets.SF_USERNAME }}" >> $HOME/.snowsql/config
          echo "password = ${{ secrets.SF_PASSWORD }}" >> $HOME/.snowsql/config
          echo "database = ${{ secrets.SF_DATABASE }}" >> $HOME/.snowsql/config
          echo "warehouse = ${{ secrets.SF_WAREHOUSE }}" >> $HOME/.snowsql/config
          echo "role = ${{ secrets.SF_ROLE }}" >> $HOME/.snowsql/config

      - name: Verify SnowSQL Configuration
        run: |
          snowsql -c snowflake_connect -q "SELECT CURRENT_VERSION();"

      # Step 4: Run each modified SQL file on Snowflake using SnowSQL
      - name: Execute SQL Files on Snowflake
        if: env.sql_files != ''
        run: |
          while read sql_file; do
            echo "Running $sql_file"
            echo "Executing $sql_file on Snowflake..."
            snowsql -c snowflake_connect -f "$sql_file"
          done < modified_sql_files.txt
