name: Run Modified SQL Files on Snowflake

on:
  push:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  run-modified-sql:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SnowSQL
      run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Create SnowSQL Configuration
      run: |
          mkdir -p $HOME/.snowsql
          echo "[connections.default]" > $HOME/.snowsql/config
          echo "accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $HOME/.snowsql/config
          echo "username = ${{ secrets.SNOWFLAKE_USER }}" >> $HOME/.snowsql/config
          echo "password = ${{ secrets.SNOWFLAKE_PASSWORD }}" >> $HOME/.snowsql/config
          echo "database = ${{ secrets.SNOWFLAKE_DATABASE }}" >> $HOME/.snowsql/config
          echo "warehouse = ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> $HOME/.snowsql/config
          echo "role = ${{ secrets.SNOWFLAKE_ROLE }}" >> $HOME/.snowsql/config
          
    - name: Check SnowSQL Installation
      run: |
            echo $PATH  # Verify that the path includes ~/bin
            which snowsql  # This should now return the path to the snowsql executable
            snowsql --version  # Confirm that SnowSQL is installed and working
            snowsql --help

    - name: Configure SnowSQL
      run: |
            mkdir -p ~/.snowsql  # Create the .snowsql directory if it doesn't exist
            echo "[connections]" > ~/.snowsql/config  # Start the config file
            echo "accountname = $SNOWFLAKE_ACCOUNT" >> ~/.snowsql/config
            echo "username = $SNOWFLAKE_USER" >> ~/.snowsql/config
            echo "password = $SNOWFLAKE_PASSWORD" >> ~/.snowsql/config
            echo "warehouse = $SNOWFLAKE_WAREHOUSE" >> ~/.snowsql/config
            echo "database = $SNOWFLAKE_DATABASE" >> ~/.snowsql/config
            echo "role = $SNOWFLAKE_ROLE" >> ~/.snowsql/config

    # Step 2: Detect modified SQL files between the current and previous commits
    - name: Detect Modified SQL Files
      id: modified_files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.sql' > modified_sql_files.txt
        # Set the output if any SQL files were found
          if [ -s modified_sql_files.txt ]; then
            # Set the output for later use
            echo "sql_files=$(cat modified_sql_files.txt)" >> $GITHUB_ENV
          else
            echo "No SQL files modified."
            echo "sql_files=" >> $GITHUB_ENV
          fi
        
     # Step 3: Print the output of the previous step
    - name: Print Modified SQL Files
      run: |
          echo "The modified SQL files are: ${{ env.sql_files }}"

    # Step 4: Run each modified SQL file on Snowflake using SnowSQL
    - name: Execute SQL Files on Snowflake
      if: env.sql_files != ''
      run: |
        while read sql_file; do
        echo "Running $sql_file"
        echo "Executing $sql_file on Snowflake..."
        
        snowsql -c default

        
        done < modified_sql_files.txt
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
