name: Run Modified SQL Files on Snowflake

on:
  push:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  run-modified-sql:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install SnowSQL
      run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash


    # Step 2: Detect modified SQL files between the current and previous commits
    - name: Detect Modified SQL Files
      id: modified_files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.sql' > modified_sql_files.txt
        # Set the output if any SQL files were found
          if [ -s modified_sql_files.txt ]; then
            # Set the output for later use
            echo "sql_files=$(cat modified_sql_files.txt)" >> $GITHUB_ENV
          else
            echo "No SQL files modified."
            echo "sql_files=" >> $GITHUB_ENV
          fi
        
     # Step 3: Print the output of the previous step
    - name: Print Modified SQL Files
      run: |
          echo "The modified SQL files are: ${{ env.sql_files }}"

    # Step 4: Run each modified SQL file on Snowflake using SnowSQL
    - name: Execute SQL Files on Snowflake
      if: env.sql_files != ''
      run: |
        while read sql_file; do
        echo "Running $sql_file"
          echo "Executing $sql_file on Snowflake..."
          ~/bin/snowsql -a $SNOWFLAKE_ACCOUNT \
                        -u $SNOWFLAKE_USER \
                        -p $SNOWFLAKE_PASSWORD \
                        -d $SNOWFLAKE_DATABASE \
                        -r $SNOWFLAKE_ROLE \
                        -w $SNOWFLAKE_WAREHOUSE \
                        -f "$sql_file"
        done < modified_sql_files.txt
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
